Show Change logs on App update
horizontalsystems/unstoppable-wallet-android pull request #3518
Opened 2021-04-08 05:40 UTC by rafaelekol

ref  #3452

2021-04-08 06:27 UTC, abdrasulov requested changes

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ChangeLogsManager.kt
> +            val currentMinorVersion = currentAppVersion.split(".").getOrNull(1)?.toIntOrNull() ?: return false
It's better to have the logic for determining version data into Version class

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ChangeLogsManager.kt
> +        return "file:///changelogs/changelog21.md"
Should the version number be in the name of file?

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
> +    override var lastAppVersion: String?
Can we use the existing `appVersions` instead?

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
> +            delay(2000)
Let's move the delay into the if block. Otherwise it will delay even if it doesn't show the changelog.

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownContentProvider.kt
> +            else -> throw Exception("Invalid protocol")
Can we show what protocol is invalid?

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownFragment.kt
> +            return
Do we need return here?

2021-04-08 06:27 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownViewModel.kt
> +    private fun getContent(contentUrl: String): Single<String> {
Let's inline this method

2021-04-08 11:38 UTC, rafaelekol commented on app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownFragment.kt
> +            return
Yes, we do need it here.

2021-04-09 05:56 UTC, abdrasulov approved these changes

2021-04-09 06:20 UTC, tmedetbekov approved these changes

2021-04-09 06:21 UTC, merged