Fix crash with CustomSnackbar in Market pages
horizontalsystems/unstoppable-wallet-android pull request #3803
Opened 2021-06-02 12:35 UTC by rafaelekol

ref #3796

2021-06-02 12:40 UTC, omurovch submitted a review, later dismissed

2021-06-02 12:48 UTC, abdrasulov commented on core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
>          val snackbar = CustomSnackbar.make(contenView as ViewGroup, text, backgroundColor, duration, gravity, showProgressBar)
There is another issue here. `contentView` is `View`, but we expect it to be `ViewGroup`. Should we set its type to `ViewGroup`?

2021-06-02 12:49 UTC, abdrasulov requested changes
See comments

2021-06-04 07:49 UTC, abdrasulov approved these changes

2021-06-04 08:05 UTC, omurovch approved these changes

2021-06-04 08:05 UTC, merged