Fix ZCash empty memo field in Transaction Info module
horizontalsystems/unstoppable-wallet-android pull request #4013
Opened 2021-08-05 12:19 UTC by rafaelekol

ref #3997

2021-08-05 12:48 UTC, abdrasulov commented on app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransaction.kt
> +            "Unable to parse memo."
Maybe we should return null in this case?

2021-08-05 12:48 UTC, abdrasulov requested changes
See comment

2021-08-06 04:47 UTC, abdrasulov approved these changes

2021-08-06 05:18 UTC, tmedetbekov approved these changes

2021-08-06 05:20 UTC, merged