Handle optional Coin Audit Report links
horizontalsystems/unstoppable-wallet-android pull request #4455
Opened 2021-12-20 05:53 UTC by rafaelekol

- Set version code to 55
- Set version name to 0.23.1

2021-12-20 05:55 UTC, ealymbaev approved these changes

2021-12-20 05:57 UTC, abdrasulov approved these changes

2021-12-20 06:01 UTC, omurovch approved these changes

2021-12-20 06:02 UTC, merged

2022-05-01 16:57 UTC, TanakronLaothong requested changes
[]()

2022-05-15 13:04 UTC, TanakronLaothong requested changes
[]()